import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service — upto." };

const LAST_UPDATED = "June 3, 2025";
const CONTACT_EMAIL = "upto.mgmt@gmail.com";
const APP_URL = "https://www.getupto.io";

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-20 space-y-10">
      <div className="space-y-2">
        <h1 className="text-3xl font-semibold tracking-tight">Terms of Service</h1>
        <p className="text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>
      </div>

      <Section title="Agreement">
        <p>
          By creating an account at{" "}
          <a href={APP_URL} className="underline underline-offset-2">{APP_URL}</a>,
          you agree to these Terms of Service. If you do not agree, do not use the service.
          For questions, contact{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} className="underline underline-offset-2">{CONTACT_EMAIL}</a>.
        </p>
      </Section>

      <Section title="The service">
        <p>
          upto. is an AI-powered email digest service. We aggregate newsletters and RSS
          feeds you subscribe to, remove duplicate content, and deliver a single
          personalized briefing on your chosen schedule.
        </p>
        <p>
          The service is provided &ldquo;as is.&rdquo; We do our best to deliver reliable,
          high-quality digests, but we do not guarantee uninterrupted availability or
          that digest content will be error-free.
        </p>
      </Section>

      <Section title="Your account">
        <ul className="list-disc pl-5 space-y-2">
          <li>You must be at least 16 years old to use upto.</li>
          <li>You are responsible for keeping your login credentials secure.</li>
          <li>You may not share your account with others or create accounts on behalf of third parties without their consent.</li>
          <li>One account per person. Duplicate accounts may be merged or removed.</li>
        </ul>
      </Section>

      <Section title="Acceptable use">
        <p>You agree not to use upto. to:</p>
        <ul className="list-disc pl-5 space-y-1 mt-2">
          <li>Route spam, phishing emails, or illegal content to your inbound address</li>
          <li>Attempt to reverse-engineer, scrape, or abuse the API</li>
          <li>Circumvent subscription limits or billing</li>
          <li>Violate any applicable laws or regulations</li>
        </ul>
        <p className="mt-3">
          We reserve the right to suspend or terminate accounts that violate these terms
          without prior notice.
        </p>
      </Section>

      <Section title="Subscriptions and billing">
        <p>
          Paid plans are billed monthly through Creem, our payment processor.
          Prices are shown in USD and may be subject to local taxes.
        </p>
        <ul className="list-disc pl-5 space-y-2 mt-2">
          <li><strong>Free trial</strong> — where offered, the trial period is stated at signup. No charge until the trial ends.</li>
          <li><strong>Cancellation</strong> — you may cancel at any time from your account page. Access continues until the end of the current billing period. No refunds for partial months.</li>
          <li><strong>Price changes</strong> — we will notify you at least 30 days before raising prices. You may cancel before the change takes effect.</li>
        </ul>
      </Section>

      <Section title="Your content">
        <p>
          You retain ownership of any content routed through upto. (newsletters, RSS items,
          replies). You grant us a limited license to process that content for the sole
          purpose of generating your digest. We do not claim any rights to your content
          and do not share it with third parties except as required to operate the service
          (see our Privacy Policy).
        </p>
      </Section>

      <Section title="Intellectual property">
        <p>
          The upto. name, logo, and service design are our intellectual property.
          You may not reproduce or use them without written permission.
        </p>
        <p>
          Digest summaries are generated by AI and are provided for personal use only.
          The underlying source content belongs to the original publishers.
        </p>
      </Section>

      <Section title="Limitation of liability">
        <p>
          To the maximum extent permitted by law, upto. is not liable for any indirect,
          incidental, or consequential damages arising from your use of the service,
          including missed newsletters, digest errors, or service interruptions.
          Our total liability to you will not exceed the amount you paid us in the
          three months preceding the claim.
        </p>
      </Section>

      <Section title="Governing law">
        <p>
          These terms are governed by the laws of the State of Israel, without regard
          to conflict of law principles. Disputes will be resolved in the courts of
          Tel Aviv, Israel.
        </p>
      </Section>

      <Section title="Changes to these terms">
        <p>
          We may update these terms. We will notify active users by email at least
          14 days before material changes take effect. Continued use of the service
          after that date constitutes acceptance of the new terms.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Questions about these terms?{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} className="underline underline-offset-2">{CONTACT_EMAIL}</a>
        </p>
      </Section>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-lg font-semibold">{title}</h2>
      <div className="text-sm text-muted-foreground leading-relaxed space-y-2">
        {children}
      </div>
    </section>
  );
}
